name: ran_flutter_core
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ç½‘ç»œè¯·æ±‚ ðŸ¦Š
  dio: ^3.0.1
  # State ðŸ¦„
  provider: 4.0.3
  # æ•°æ®å­˜å‚¨ ðŸ¦Œ
  shared_preferences: ^0.5.3+5
  # æœ¬åœ°jsonå¯¹è±¡å­˜å‚¨
  localstorage: ^2.0.0
  # è·¯ç”±æ¡†æž¶
  fluro: ^1.7.0
  # Dartå¸¸ç”¨å·¥å…·ç±»åº“
  common_utils: ^1.2.1
  #  cached_network_image: ^1.1.1
  cached_network_image: ^2.0.0-rc.1
  # third_app å¯åŠ¨ç¬¬ä¸‰æ–¹app
  url_launcher: ^5.5.0
  # åˆ†äº«
  share: 0.6.2+1
  # æ‰«ç 
  qrscan: ^0.2.17
  # UI å…¨å±€æç¤º
  oktoast: ^2.3.1
  # å¤„ç†é”®ç›˜äº‹ä»¶ ðŸ¡
  keyboard_actions: ^2.1.2
  # åŒ…ä¿¡æ¯ ðŸŒ‹
  package_info: ^0.4.0+6
  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3
  # è®¾å¤‡ä¿¡æ¯ ðŸ“ƒ
  device_info: ^0.4.0+1
  # å…¨å±€æç¤º ðŸ¨
  fluttertoast: ^3.1.0
  # å…¨å±€loading ðŸ®
  flutter_easyloading: ^2.0.0
  # ç½‘é¡µ ðŸº
  webview_flutter: ^1.0.3
  # ç½‘é¡µ ðŸ³
  flutter_webview_plugin: ^0.3.11
  # å›¾ç‰‡é¢„è§ˆ ðŸ¼
  photo_view: ^0.10.2
  # BotToast ðŸ¤–
  bot_toast: ^3.0.4
  # æœ¬åœ°æ•°æ®åº“
  sqflite: ^1.3.0
  # æ–‡ä»¶è·¯å¾„
  path_provider: ^1.6.22
dev_dependencies:
  flutter_test:
    sdk: flutter
  # å…¨å±€æç¤ºðŸ²
  fluttertoast: ^3.1.0
  # ä¸‹æ‹‰åˆ·æ–°ï¼Œä¸Šæ‹‰åŠ è½½
  pull_to_refresh: ^1.5.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  assets:
    - packages/ran_flutter_core/assets/images/close.png
