name: litecaijing
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # State
  provider: 4.0.3

  # Base Component
  # WebView iOSæ·»åŠ é”®å€¼å¯¹ o.flutter.embedded_views_preview = YES
  #  webview_flutter: ^0.3.19
  #  flutter_webview_plugin: ^0.3.10
  device_info: ^0.4.0+1
  package_info: ^0.4.0+6
  quiver: ^2.0.5
  #  connectivity: ^0.4.3+6

  # Data
  #  json_annotation: ^2.4.0
  dio: ^3.0.1
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  shared_preferences: ^0.5.3+5
  # æœ¬åœ°jsonå¯¹è±¡å­˜å‚¨
  localstorage: ^2.0.0

  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3
  # è§£æžhtmlæ ‡ç­¾
  flutter_html: ^0.10.4

  # åˆ¤æ–­listæ˜¯å¦ç›¸ç­‰
  collection: ^1.14.11
  #  crypto: ^2.0.6

  # UI
  oktoast: ^2.3.1
  pull_to_refresh: ^1.6.3
  flutter_swiper: ^1.1.6
  #  cached_network_image: ^1.1.1
  cached_network_image: ^2.0.0-rc.1
  # ç±»iOSä¾§æ»‘èœå•
  flutter_slidable: 0.5.3
  # è°ç”¨è°é—ªäº®
  shimmer: ^1.0.0
  # è¯†åˆ«å›¾ç‰‡çš„ä¸»è¦é¢œè‰²
  #  palette_generator: ^0.2.0
  # æ›´æ–°å±•ç¤ºæ”¯æŒmark_down
  flutter_markdown: ^0.2.0
  flare_flutter: ^1.5.9

  # third_app
  url_launcher: ^5.1.6 #å¯åŠ¨ç¬¬ä¸‰æ–¹app
  share: 0.6.2+1 #åˆ†äº«
  launch_review: ^2.0.0
  open_file: ^2.0.3

  # androidæƒé™å¼¹çª—
  #  permission_handler: ^3.2.2

  # ä¸ŠæŠ¥ ç›®å‰é—®é¢˜æ¯”è¾ƒå¤š
  #  flutter_bugly: 0.2.7

  # Dart å¸¸ç”¨å·¥å…·ç±»åº“ https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # å¸é¡¶
  sticky_headers: ^0.2.0
  # ç½‘é¡µ ðŸº
  webview_flutter: ^1.0.3
  # å…¨å±€æç¤º ðŸ¨
  fluttertoast: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  sharesdk_plugin: 1.2.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile # ç«™é…· å¿«ä¹å­—ä½“  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
  assets:
    - assets/images/
    - assets/images/tabbar/
    - assets/images/statistic/
